# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "pip" # Specify "pip" for Python projects using requirements.txt
    directory: "/" # Location of the requirements.txt file, assuming it's in the root folder
    schedule:
      interval: "weekly" # Checks for updates once a week
      
